#
# for huaqin misc info
#
# Tab A9_BOS code for AX6739W-11 by Liushiyuan at 20250607 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK)   += sim_tray/
# Tab A9_BOS code for AX6739W-11 by Liushiyuan at 20250607 end
# Tab A9 code for SR-AX6739A-01-371 by tangyuhang at 20230526 start
obj-$(CONFIG_TRIGGER_CRASH_BY_KEY)	+= combine_key/
# Tab A9 code for SR-AX6739A-01-371 by tangyuhang at 20230526 end
obj-$(CONFIG_HPERF_ENABLE)   += hperf/