# SPDX-License-Identifier: GPL-2.0
#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y				+= mediatek/

obj-y				+= huaqin/

# Tab A9 code for SR-AX6739A-01-392 by gaochao at 20230426 start
obj-$(CONFIG_GRDM_POWER)        += grdm/
obj-$(CONFIG_KNOXVAULT_POWER)        += KnoxVault/
obj-$(CONFIG_I2C_KNOXVAULTDEV)        += KnoxVaultDev/
# Tab A9 code for SR-AX6739A-01-392 by gaochao at 20230426 end

