#
# for huaqin misc info
#
# Tab A9_BOS code for AX6739W-11 by Liushiyuan at 20250607 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK) += sim_tray.o
# Tab A9_BOS code for AX6739W-11 by Liushiyuan at 20250607 end
