obj-$(CONFIG_DRM_LCD_HX83102E_LC_HKC_VIDEO_HST11) += lcd_hx83102e_lc_hkc_video_hst11.o
obj-$(CONFIG_DRM_LCD_HX83102G_XY_INX_VIDEO) += lcd_hx83102g_xy_inx_video.o
obj-$(CONFIG_DRM_LCD_JD9366TC_XY_CSOT_VIDEO) += lcd_jd9366tc_xy_csot_video.o
obj-$(CONFIG_DRM_LCD_JD9366TC_LD_HKC_VIDEO) += lcd_jd9366tc_ld_hkc_video.o
obj-$(CONFIG_DRM_LCD_DEFAULT_MIPI_FHD_VIDEO_HST11) += lcd_default_mipi_fhd_video_hst11.o